proxy:
  image: avilaplana/tvlive-nginx
  links:
  - api:tv-api
  ports:
  - "80:80"
api:
  image: avilaplana/tvlive-api
  links:
   - db:mongo
   - auth:tvlive-auth
  environment:
    HOST_TVLIVE: http://TO_FILL_BY_USER
auth:
  image: avilaplana/tvlive-auth
  links:
   - db:mongo
crawler:
  image: avilaplana/tvlive-crawler
  links:
  - db:mongo
db:
  image: mongo
